### ISSUE TITLE
stage = 'no' issue

### ISSUE THREAD

**Issue by chwjshlwel** [haoningwu3639/StoryGen#14]
when I use the stage = 'no', the following error occurs.
Traceback (most recent call last):
File "D:\AIGC\StoryGen-master\inference.py", line 139, in
test(pretrained_model_path,
File "D:\AIGC\StoryGen-master\inference.py", line 103, in test
output = pipeline(
File "C:\Users\chwj0\miniconda3\envs\ldm\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
return func(*args, **kwargs)
File "D:\AIGC\StoryGen-master\model\pipeline.py", line 443, in call
for k,v in img_conditions[0].items():
AttributeError: 'NoneType' object has no attribute 'items'

**Comment by lq-blackcat** [comment]
You need to set stage='multi-image-condition' or stage='auto-regressive' for img_conditions to have a non-empty value.

**Comment by chwjshlwel** [comment]
https://github.com/haoningwu3639/StoryGen/issues/10#issuecomment-1990966054
Here they said if want to generate a story, we should set stage='no'

I fact, I want to generate a story like the Fig. 1 in the paper, but I do not know how to do it.
When set stage='multi-image-condition' or stage='auto-regressive', the generated images are so different and not consistent.

**Comment by haoningwu3639** [comment]
To generate the first frame of the story, you need to set stage = 'no', because there is no existing conditional frame yet.
Later, you can use the generated first frame as a condition to auto-regressive synthesize the story, that is, set stage = 'multi-image-condition' or stage = 'auto-regressively'.
Additionally, as mentioned in previous issues (https://github.com/haoningwu3639/StoryGen/issues/10#issuecomment-2002906594).  'descriptive text' is more suitable to serve as a prompt than 'narrative story text'. Thus, we also mentioned in our paper that we should use ChatGPT or GPT-4 (or an open-source LLM such as LLaMA) to convert the storylines into corresponding descriptions as input to the model. We recommend you do the same.

**Comment by lq-blackcat** [comment]
@haoningwu3639 AttributeError: 'NoneType' object has no attribute 'items'，[this](https://github.com/haoningwu3639/StoryGen/issues/14#issuecomment-2021797561) does not explain how to solve this problem.

**Comment by Verg-Avesta** [comment]
Please refer to https://github.com/haoningwu3639/StoryGen/issues/10#issuecomment-1993808245 .
When using **stage='no'**, you should use a random **prev_p** and **ref_image** instead of empty ones. The model will not extract and attend to their features when stage = 'no'.

**Comment by EIKO1241** [comment]
Hi!I set the stage="no" and set the prev_p=["The yellow-haired man"] and ref_image=["/gemini/code/StoryGen/data/boy.png"] instead of empty ones.But the error that "nonetype" object has no attribute "items" remains.How should I fix it?
![image](https://github.com/haoningwu3639/StoryGen/assets/166361197/6c84e64a-5719-4ecd-b099-2a0569157d13)

**Comment by Verg-Avesta** [comment]
Sorry, I just found a bug in pipeline.py and fixed it. Please use the new pipeline.py .
Now when using **stage='no'** with a random **prev_p** and **ref_image**, you can generate the correct result.
