### ISSUE TITLE
Inference results didn't perform as expected

### ISSUE THREAD

**Issue by yliyli** [haoningwu3639/StoryGen#25]
Hi Haoning,

I was trying inference.py, annd the results seem to be underperforming. I was wondering if you could help me check if I did everything correctly. I downloaded checkpoint_Story from https://huggingface.co/haoningwu/StoryGen/tree/main, and downloaded all requirements from environmenbt.yaml with some problems with packages that required c++ (libtorch_cuda_cu.so and xformers). Then I ran with these parameters: 
<img width="1016" alt="image" src="https://github.com/haoningwu3639/StoryGen/assets/77973600/b95948b1-2622-4541-85cd-57b4e0ea87a5">

The results looked somewhat like this: 
<img width="459" alt="image" src="https://github.com/haoningwu3639/StoryGen/assets/77973600/682b6795-6ca8-430e-9300-c2b992622fbb">

The boy and the dog are all very different from the images I provided. Could you give more guide in terms of how to use inference.py, difference between "multi-image-condition" and "auto-regressive", and if I used the inputs correctly? Or these degradation are results from the c++ packages? I feel that's less likely though, since they appear to be packages for efficiency.

Thanks a lot!

**Comment by haoningwu3639** [comment]
Sorry for the late response, it seems that you are trying to generate with multiple reference characters, which is a more challenging problem. In the supplementary of our paper, we provide an example of multi-character generation, but it is slightly less stable than single-character generation because we have not trained specifically for this situation.
Also, I recommend you use auto-regressive manner rather than multi-image-condition.
