### ISSUE TITLE
Checkpoint 

### ISSUE THREAD

**Issue by HranushS** [haoningwu3639/StoryGen#36]
Hi, seems like the checkpoint link is invalid, as I can not find the model in the diffusers library, can you please send the valid link?Thanks.

**Comment by haoningwu3639** [comment]
Since we have modified the architecture of diffusion UNet, you need to manually download the checkpoint from _https://huggingface.co/haoningwu/StoryGen/tree/main/checkpoint_StorySalon_ or _https://huggingface.co/haoningwu/StoryGen/tree/main/checkpoint_COCO,_ and use the inference code we provided to load the model instead of directly using diffusers' AutoModel for automatic recognition.

**Comment by haoningwu3639** [comment]
Ahaha! It looks like the download link for the Stable Diffusion v1.5 checkpoint has been moved to a new repository. I have updated the download link accordingly.
