### ISSUE TITLE
loss of image_inpainted_finally_checked

### ISSUE THREAD

**Issue by JYMiracle305** [haoningwu3639/StoryGen#42]
Why still miss files after downloading the latest dataset

(https://huggingface.co/datasets/haoningwu/StorySalon/blob/main/StorySalon.zip)

 No such file or directory: './StorySalon/image_inpainted_finally_checked'

Could you provide the contents of all files in StorySalon

**Comment by JYMiracle305** [comment]
![image](https://github.com/user-attachments/assets/7ac6a5b5-2a95-486a-8bfa-a61fb2542c94)

**Comment by JYMiracle305** [comment]
I would like to ask specifically how to place the data. For example, in StorySalon and testSet, I keep all the contents of StorySalon and put the video part of testSet into /StorySalon/image_inpainted_finally_checked, /StorySalon/mask, and /StorySalon/Text/Video respectively, but an error will be reported.
![image](https://github.com/user-attachments/assets/ccabd528-35ab-47bb-8410-cc0ba76b4692)

**Comment by haoningwu3639** [comment]
Sorry for the delayed response; I was busy with some other paper submissions.

We have already provided the data processing pipeline for StorySalon. Due to potential copyright concerns, we cannot directly provide all the video files. However, we do offer downloadable images from open-source libraries. You can follow the curation pipeline we provided to process and clean the data. The final processed images should be stored in the `image_inpainted_finally_checked folder`.

To facilitate reproducibility and simplify the data processing workflow, we have also included the index files (in txt/json format) of the processed data.
