### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by enterprisium** [haoningwu3639/StoryGen#9]
I am a newbie and  I was looking for a project that can convert my audio book into video based on the transcription. I didn't wrote the complete paper because that confuses me so I am asking here to get help from you. The question is... m I at the. Right place? I mean do this project is what I am looking for? Can this project can change my audiobook into visual videos?. If not can you please refer any other project ? Thanks alot for ur time and consideration.

**Comment by haoningwu3639** [comment]
Sorry for the late reply, we have recently updated our code and data set. Our approach is a partial solution to your problem, that is, you can convert audio books to text (for example, through WhisperX) and then feed the text into our model to autoregressively generate the corresponding picture-book style story. However, it should be noted that due to the limitations of data and computing power, our model can generate a coherent image sequence (key frame), but it is not yet able to generate a video that can be played.
